// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package bank

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BankClient is the client API for Bank service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BankClient interface {
	Create(ctx context.Context, in *BankCreateRequest, opts ...grpc.CallOption) (*BankCreateReply, error)
	Update(ctx context.Context, in *BankUpdateRequest, opts ...grpc.CallOption) (*BankUpdateReply, error)
	GetAll(ctx context.Context, in *BankGetAllRequest, opts ...grpc.CallOption) (*BankGetAllReply, error)
	GetByID(ctx context.Context, in *BankGetByIDRequest, opts ...grpc.CallOption) (*BankGetByIDReply, error)
}

type bankClient struct {
	cc grpc.ClientConnInterface
}

func NewBankClient(cc grpc.ClientConnInterface) BankClient {
	return &bankClient{cc}
}

func (c *bankClient) Create(ctx context.Context, in *BankCreateRequest, opts ...grpc.CallOption) (*BankCreateReply, error) {
	out := new(BankCreateReply)
	err := c.cc.Invoke(ctx, "/bank.Bank/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) Update(ctx context.Context, in *BankUpdateRequest, opts ...grpc.CallOption) (*BankUpdateReply, error) {
	out := new(BankUpdateReply)
	err := c.cc.Invoke(ctx, "/bank.Bank/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) GetAll(ctx context.Context, in *BankGetAllRequest, opts ...grpc.CallOption) (*BankGetAllReply, error) {
	out := new(BankGetAllReply)
	err := c.cc.Invoke(ctx, "/bank.Bank/GetAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bankClient) GetByID(ctx context.Context, in *BankGetByIDRequest, opts ...grpc.CallOption) (*BankGetByIDReply, error) {
	out := new(BankGetByIDReply)
	err := c.cc.Invoke(ctx, "/bank.Bank/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BankServer is the server API for Bank service.
// All implementations must embed UnimplementedBankServer
// for forward compatibility
type BankServer interface {
	Create(context.Context, *BankCreateRequest) (*BankCreateReply, error)
	Update(context.Context, *BankUpdateRequest) (*BankUpdateReply, error)
	GetAll(context.Context, *BankGetAllRequest) (*BankGetAllReply, error)
	GetByID(context.Context, *BankGetByIDRequest) (*BankGetByIDReply, error)
	mustEmbedUnimplementedBankServer()
}

// UnimplementedBankServer must be embedded to have forward compatible implementations.
type UnimplementedBankServer struct {
}

func (UnimplementedBankServer) Create(context.Context, *BankCreateRequest) (*BankCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedBankServer) Update(context.Context, *BankUpdateRequest) (*BankUpdateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedBankServer) GetAll(context.Context, *BankGetAllRequest) (*BankGetAllReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedBankServer) GetByID(context.Context, *BankGetByIDRequest) (*BankGetByIDReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (UnimplementedBankServer) mustEmbedUnimplementedBankServer() {}

// UnsafeBankServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BankServer will
// result in compilation errors.
type UnsafeBankServer interface {
	mustEmbedUnimplementedBankServer()
}

func RegisterBankServer(s grpc.ServiceRegistrar, srv BankServer) {
	s.RegisterService(&Bank_ServiceDesc, srv)
}

func _Bank_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank.Bank/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).Create(ctx, req.(*BankCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank.Bank/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).Update(ctx, req.(*BankUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankGetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank.Bank/GetAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).GetAll(ctx, req.(*BankGetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Bank_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BankGetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BankServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/bank.Bank/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BankServer).GetByID(ctx, req.(*BankGetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Bank_ServiceDesc is the grpc.ServiceDesc for Bank service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Bank_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bank.Bank",
	HandlerType: (*BankServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Bank_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Bank_Update_Handler,
		},
		{
			MethodName: "GetAll",
			Handler:    _Bank_GetAll_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _Bank_GetByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bank.proto",
}
